/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import Backend.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
/**
 *
 * @author lenovo
 */
public class Fine extends javax.swing.JFrame {

    /**
     * Creates new form Fine
     */
    int fineAmt = 0;
    int customerId;
    public Fine(int custId, int fine) {
        initComponents();
        fineAmt = fine;
        customerId= custId;
        txtFineAmt.setText(fineAmt+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngpModeofTransaction = new javax.swing.ButtonGroup();
        lblFine = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rbtnDebit = new javax.swing.JRadioButton();
        rbtnCredit = new javax.swing.JRadioButton();
        lblCardNumber = new javax.swing.JLabel();
        txtCardNumber = new javax.swing.JTextField();
        lblCvv = new javax.swing.JLabel();
        txtCvv = new javax.swing.JTextField();
        lblDateOfExpiry = new javax.swing.JLabel();
        btnPay = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        dtcExpiryDate = new com.toedter.calendar.JDateChooser();
        lblFineAmt = new javax.swing.JLabel();
        txtFineAmt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fine");

        lblFine.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        lblFine.setText("Pay Fine");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Choose Mode of Transaction: ");

        btngpModeofTransaction.add(rbtnDebit);
        rbtnDebit.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        rbtnDebit.setText("Debit Card");
        rbtnDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDebitActionPerformed(evt);
            }
        });

        btngpModeofTransaction.add(rbtnCredit);
        rbtnCredit.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        rbtnCredit.setText("Credit Card");
        rbtnCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCreditActionPerformed(evt);
            }
        });

        lblCardNumber.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblCardNumber.setText("Card Number: ");

        txtCardNumber.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtCardNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCardNumberKeyTyped(evt);
            }
        });

        lblCvv.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblCvv.setText("CVV:");

        txtCvv.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtCvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCvvActionPerformed(evt);
            }
        });
        txtCvv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCvvKeyTyped(evt);
            }
        });

        lblDateOfExpiry.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblDateOfExpiry.setText("Date of Expiry:");

        btnPay.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnPay.setText("Pay");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        dtcExpiryDate.setDateFormatString("dd/MM/yyyy");
        dtcExpiryDate.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        lblFineAmt.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblFineAmt.setText("Fine Amount: ");

        txtFineAmt.setEditable(false);
        txtFineAmt.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnBack)
                .addGap(482, 482, 482)
                .addComponent(lblFine)
                .addContainerGap(432, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPay)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblFineAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(211, 211, 211))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblCardNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDateOfExpiry, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCvv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCvv)
                                    .addComponent(txtCardNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(dtcExpiryDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFineAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(276, 276, 276))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbtnCredit, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(rbtnDebit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblFine))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnDebit)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addComponent(rbtnCredit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardNumber)
                    .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCvv)
                    .addComponent(txtCvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDateOfExpiry)
                    .addComponent(dtcExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFineAmt)
                    .addComponent(txtFineAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(232, 232, 232)
                .addComponent(btnPay)
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean verifyExpiryDate(){
        Date today = new Date();
        Date exp = dtcExpiryDate.getDate();
        if(exp.after(today))
            return true;
        return false;
    }
    
    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        
        if(btngpModeofTransaction.getSelection() == null)
            JOptionPane.showMessageDialog(Fine.this, "Select a mode of transaction");
        else if(txtCardNumber.getText().trim().isEmpty())
            JOptionPane.showMessageDialog(Fine.this, "Enter a valid card number");
        else if(txtCvv.getText().trim().isEmpty() || txtCvv.getText().length() != 3)
            JOptionPane.showMessageDialog(Fine.this, "Enter a valid CVV");
        else if(dtcExpiryDate.getDate() == null){
            JOptionPane.showMessageDialog(Fine.this, "Enter expiry date");
        }
        else if(verifyExpiryDate() == false){
            JOptionPane.showMessageDialog(Fine.this, "Card has expired");
        }
        else{
            LocalDate today = LocalDate.now();
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            String date = today.format(dtf);
            FineBackend fb = new FineBackend();
            //System.out.println(date);
            fb.addFine(customerId, fineAmt, date);
            fb.removeFine(customerId);
            txtCardNumber.setText("");
            txtCvv.setText("");
            btngpModeofTransaction.clearSelection();
            txtFineAmt.setText("");
            CustomerDashboard.currentCustomer.fine=0;
            new BookBackend().updateBorrow(customerId);
            JOptionPane.showMessageDialog(Fine.this, "Payment Successful");
        }
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new CustomerDashboard("").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCardNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCardNumberKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE))
            evt.consume();
    }//GEN-LAST:event_txtCardNumberKeyTyped

    private void txtCvvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCvvKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE))
            evt.consume();
    }//GEN-LAST:event_txtCvvKeyTyped

    private void txtCvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCvvActionPerformed

    private void rbtnCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCreditActionPerformed

    private void rbtnDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDebitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDebitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fine(-1, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPay;
    private javax.swing.ButtonGroup btngpModeofTransaction;
    private com.toedter.calendar.JDateChooser dtcExpiryDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JLabel lblCvv;
    private javax.swing.JLabel lblDateOfExpiry;
    private javax.swing.JLabel lblFine;
    private javax.swing.JLabel lblFineAmt;
    private javax.swing.JRadioButton rbtnCredit;
    private javax.swing.JRadioButton rbtnDebit;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtCvv;
    private javax.swing.JTextField txtFineAmt;
    // End of variables declaration//GEN-END:variables
}
